name: Deploy to Yandex Cloud

on:
  push:
    branches:
      - develop

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 111.88.246.148
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd diplom
            git pull origin develop
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up --build -d
            docker compose -f docker-compose.prod.yml exec -T app python manage.py migrate --noinput
            docker compose -f docker-compose.prod.yml exec -T app python manage.py collectstatic --noinput
